using System.Collections.Immutable;
using System.Text;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MonoGameEngine.Generators;

[Generator]
public class BootstrapperGenerator : IIncrementalGenerator
{
    private struct MethodData
    {
        public string FullName;
        public int Priority;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Get the assembly name
        var assemblyNameProvider = context.CompilationProvider.Select((compilation, _) => compilation.AssemblyName);

        // 2. Find all methods with [OnInitialize]
        var initMethods = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
                transform: (ctx, _) => GetMethodIfHasAttribute(ctx, "OnInitialize"))
            .Where(m => m.HasValue)
            .Select((m, _) => m.Value)
            .Collect();

        // 3. Find all methods with [ContentLoad]
        var contentMethods = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
                transform: (ctx, _) => GetMethodIfHasAttribute(ctx, "ContentLoad"))
            .Where(m => m.HasValue)
            .Select((m, _) => m.Value)
            .Collect();

        // 4. Combine all providers and generate
        var combined = initMethods.Combine(contentMethods).Combine(assemblyNameProvider);

        context.RegisterSourceOutput(combined, (spc, source) =>
        {
            var methods = source.Left;
            var assemblyName = source.Right;
            if (assemblyName != null)
            {
                GenerateCode(spc, assemblyName, methods.Left, methods.Right);
            }
        });
    }

    private static MethodData? GetMethodIfHasAttribute(GeneratorSyntaxContext context, string attributeName)
    {
        var methodDeclaration = (MethodDeclarationSyntax)context.Node;
        foreach (var attributeList in methodDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var symbolInfo = context.SemanticModel.GetSymbolInfo(attribute);
                if (symbolInfo.Symbol is IMethodSymbol attributeSymbol)
                {
                    string fullName = attributeSymbol.ContainingType.ToDisplayString();
                    if (fullName.Contains(attributeName))
                    {
                        var methodSymbol = context.SemanticModel.GetDeclaredSymbol(methodDeclaration) as IMethodSymbol;
                        if (methodSymbol == null || !methodSymbol.IsStatic) continue;

                        string methodFullName = methodSymbol.ContainingType.ToDisplayString() + "." + methodSymbol.Name;

                        int priority = 0;
                        if (attributeName == "OnInitialize" && attribute.ArgumentList != null && attribute.ArgumentList.Arguments.Count > 0)
                        {
                            var arg = attribute.ArgumentList.Arguments[0];
                            var constantValue = context.SemanticModel.GetConstantValue(arg.Expression);
                            if (constantValue.HasValue)
                            {
                                priority = (int)constantValue.Value;
                            }
                        }

                        return new MethodData { FullName = methodFullName, Priority = priority };
                    }
                }
            }
        }
        return null;
    }

    private static void GenerateCode(SourceProductionContext context, string assemblyName, ImmutableArray<MethodData> initMethods, ImmutableArray<MethodData> contentMethods)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// This file is automatically generated");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Microsoft.Xna.Framework.Content;");
        sb.AppendLine("using MonoGameEngine;");
        sb.AppendLine();

        if (assemblyName == "MonoGameEngine")
        {
            sb.AppendLine("namespace MonoGameEngine");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class Bootstrapper");
            sb.AppendLine("    {");
            sb.AppendLine("        static partial void RunGeneratedInit()");
            sb.AppendLine("        {");
            foreach (var method in initMethods.OrderBy(m => m.Priority))
            {
                sb.AppendLine("            global::" + method.FullName + "();");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        static partial void RunGeneratedContentLoad(global::Microsoft.Xna.Framework.Content.ContentManager content)");
            sb.AppendLine("        {");
            foreach (var method in contentMethods)
            {
                sb.AppendLine("            global::" + method.FullName + "(content);");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine("namespace " + assemblyName + ".Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class " + assemblyName.Replace(".", "_") + "_ModuleInitializer");
            sb.AppendLine("    {");
            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            System.Diagnostics.Debug.WriteLine(\"Running module initializer for " + assemblyName + "\");");

            if (initMethods.Length > 0)
            {
                sb.AppendLine("            global::MonoGameEngine.Bootstrapper.RegisterInit(() => {");
                foreach (var method in initMethods.OrderBy(m => m.Priority))
                {
                    sb.AppendLine("                global::" + method.FullName + "();");
                }
                sb.AppendLine("            });");
            }

            if (contentMethods.Length > 0)
            {
                sb.AppendLine("            global::MonoGameEngine.Bootstrapper.RegisterContentLoad((content) => {");
                foreach (var method in contentMethods)
                {
                    sb.AppendLine("                global::" + method.FullName + "(content);");
                }
                sb.AppendLine("            });");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        context.AddSource(assemblyName + ".GeneratedBootstrapper.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
